#!/bin/bash

# DeferredInstallFixup
# Copyright 2012-2015 Apple Inc.


plist="/Library/LaunchDaemons/com.apple.PackageKit.DeferredInstallFixup.plist"
filelist="$(/usr/bin/getconf DARWIN_USER_CACHE_DIR)/DeferredInstallFixup.file_list"
injectfse="/System/Library/PrivateFrameworks/PackageKit.framework/Versions/A/Resources/injectfse"

sleep 10
if [ -e $filelist ]; then
    $injectfse $filelist
else
    /usr/bin/logger -p install.err "PackageKit: Missing deferred install file list."
fi

rm -f $plist
rm -f $filelist

exit 0